// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eejmzsgqxdodzhctlemh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlam16c2dxeGRvZHpoY3RsZW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Mzg2MjksImV4cCI6MjA2MzAxNDYyOX0.rtjnZ6K9ZWU2FiWsjTK7GFHLKDCBhtwKYXWu-pNwml0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);